
server:
  port: 8080

spring:
  application:
    name: ai-trader

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 3000ms

ai:
  dashscope:
    api-key: ${ALI_API_KEY:}
    model-name: ${DASHSCOPE_MODEL_NAME:qwen-plus}


spring.ai:
  openai:
    api-key: ${DEEPSEEK_API_KEY:}
    base-url: ${DEEPSEEK_BASE_URL:https://api.deepseek.com}
    chat:
      options:
        model: deepseek-chat
        temperature: 0.1

excel:
  data:
    path: classpath:data/history_price.xlsx
    time-slot-column: 1
    avg-price-column: 9

logging:
  level:
    root: INFO
    com.jiwuji: DEBUG
    dev.langchain4j: DEBUG
    org.springframework.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
